source {C:/Xilinx91i/data/projnav/scripts/VsimStopServer.tcl}
-- Auto Generated by Project Navigator to simulate
-- HDL Bencher Annotated Test Bench
--
vlib work
onbreak {resume}
onerror {quit -code 99 -force}
onElabError {resume}
vcom -explicit  -93 "sreg.vhd"
vcom -explicit  -93 "reg8.vhd"
vcom -explicit  -93 "decode4.vhd"
vcom -explicit  -93 "ctrl.vhd"
vcom -explicit  -93 "count4.vhd"
vcom -explicit  -93 "receive.vhd"
vcom -explicit  -93 "waveOfreceive.ant"
vsim -t 1ps   -lib work waveOfreceive
run -all
quit -force
